export interface LoginData {
    email: string;
    password: string;
}

export interface ResponseLoginData {
    token: string;
    user: User;
}

export interface User {
    userId: number;
    fullname: string;
    email: string;
    avatar: string;
} // Generated by https://quicktype.io

export interface ResponseGetGiveaway {
    total: number;
    results: Giveaway[];
}

export interface Giveaway {
    giveawayId: number;
    title: string;
    description: string;
    giveawayDate: string;
    image: string;
    participantsLimit: number;
    createdAt: string;
    status: string;
}

export interface CreateParticipant {
    giveawayId: number;
    code: string;
    redirectUri: string;
}

export interface CreateParticipantRes {
    participantId: number;
    discordId: string;
    fullname: string;
    email: string;
    giveawayId: number;
    createdIt: string;
    status: string;
    giveaway: GiveawayTitle;
}

export interface GiveawayTitle {
    title: string;
}

export interface DashUsers {
    avatar?: string;
    email: string;
    fullname: string;
    userId: number | string;
}
