export interface LoginData {
    email: string;
    password: string;
}

export interface ResponseLoginData {
    token: string;
    user: User;
}

export interface User {
    userId: number;
    fullname: string;
    email: string;
    avatar: string;
} // Generated by https://quicktype.io

export interface ResponseGetGiveaway {
    total: number;
    results: Giveaway[];
}

export interface Giveaway {
    giveawayId: number;
    title: string;
    description: string;
    giveawayDate: string;
    image: string;
    participantsLimit: number;
    createdAt: string;
    status: string;
}
